# Name of the workflow
name: Lab09 HTTP header scanning
# How the workflow run is named in GitHub
run-name: Lab09 - ${{ github.actor }} is scanning HTTP headers 🚀
permissions: read-all
# Set your preferences for the script
defaults:
  run:
    shell: pwsh
on:
  # Make it possible to other workflows to call this
  workflow_call:
  # Make it possible to manually run this workflow
  workflow_dispatch:
jobs:
  http-header-scanning:
    runs-on: ubuntu-latest
    # Steps to actually build the application
    steps:
      - name: Install Mozilla Observatory
        run: npm install --global @mdn/mdn-http-observatory
      - name: Run Mozilla Observatory
        run: mdn-http-observatory-scan mdn.dev
