name: Lab01 Calling Templates
run-name: Lab01 - ${{ github.actor }} is calling GitHub Actions Templates 🚀
permissions: read-all
on:
  workflow_dispatch:
jobs:
  run-template:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
      # Run the template with parameters
      - id: dotnet-build
        uses: ./.github/workflows/build-dotnet-app
        with:
          folder-path: "apps/uptodate-app"
