# Name of the workflow
name: Lab12 DAST
# How the workflow run is named in GitHub
run-name: Lab12 - ${{ github.actor }} is running DAST scans 🚀
permissions: read-all
# Set your preferences for the script
defaults:
  run:
    shell: pwsh
on:
  # Make it possible to other workflows to call this
  workflow_call:
  # Make it possible to manually run this workflow
  workflow_dispatch:
jobs:
  zap-scanning:
    runs-on: ubuntu-latest
    # Steps to actually build the application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docker image
        id: docker-build
        run: Write-Host "Build docker"
          docker build -t vulnerable-app-image -f /apps/vulnerable-app/Dockerfile .
          $containerId = docker run --tty --detach vulnerable-app-image --publish 8080:8080
          $targetIp = docker inspect --format '{{ .NetworkSettings.IPAddress }}' $containerId
          Add-Content -Path $env:GITHUB_OUTPUT -Value "ZAP_TARGET_IP=$targetIp"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "ZAP_TARGET_CONTAINER_ID=$containerId"
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        env:
          ZAP_TARGET:
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # to create issues in repository
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          target: "http://${{ steps.docker-build.outputs.ZAP_TARGET_IP }}"
          cmd_options: "-a"
