# Name of the workflow
name: Lab11 SARIF
# How the workflow run is named in GitHub
run-name: Lab11 - ${{ github.actor }} is creating SARIF reports 🚀
permissions: read-all
# Set your preferences for the script
defaults:
  run:
    shell: pwsh
on:
  # Make it possible to other workflows to call this
  workflow_call:
  # Make it possible to manually run this workflow
  workflow_dispatch:
jobs:
  http-header-scanning:
    runs-on: ubuntu-latest
    # Steps to actually build the application
    steps:
      - name: Install Mozilla Observatory
        run: npm install --global @mdn/mdn-http-observatory
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Mozilla Observatory and create SARIF results
        run: ./scripts/mozilla-observatory-sarif-generator.ps1 "huuhka.net" "mdn-results.sarif"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: "mdn-results.sarif"
