name: Lab12 License check
run-name: Lab12 - ${{ github.actor }} is inspecting used licenses 🔎
permissions: read-all
on:
  workflow_call:
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "🎉 Step of the job is running on ${{ runner.os }}!"
