# Name of the workflow
name: Lab10 TLS scanning
# How the workflow run is named in GitHub
run-name: Lab10 - ${{ github.actor }} is scanning TLS ciphers 🚀
permissions: read-all
# Set your preferences for the script
defaults:
  run:
    shell: pwsh
on:
  # Make it possible to other workflows to call this
  workflow_call:
  # Make it possible to manually run this workflow
  workflow_dispatch:
jobs:
  tls-scanning:
    runs-on: ubuntu-latest
    # Steps to actually build the application
    steps:
      - name: Scan TLS for given domain
        run: |
          $scanResults = ./scripts/tlsaudit.ps1 www.zure.com
          $grade = $scanResults[0]
          $ciphers = $scanResults[1]

          Write-Host "---- CIPHERS ----"
          Write-Host $ciphers
          Write-Host "----- GRADE -----"
          Write-Host $grade
          if ($grade -ne "A") {
            # Set proper error message
            echo "::error file=scripts/tlsaudit.ps1,title=Weak ciphers detected::Weak ciphers detected with grade: $grade"
            # Error message does not fail the job, use exit 1 to actually make it fail
            exit 1
          }
