name: Lab21 SAST
run-name: Lab21 - ${{ github.actor }} is finding vulns 🔎
permissions: read-all
on:
  workflow_call:
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "🎉 Step of the job is running on ${{ runner.os }}!"
