name: Lab40 HTTP header scanning
run-name: Lab40 - ${{ github.actor }} is scanning HTTP headers 🚀
permissions: read-all
on:
  workflow_call:
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "🎉 Step of the job is running on ${{ runner.os }}!"
