name: Lab41 TLS scanning
run-name: Lab41 - ${{ github.actor }} is scanning TLS ciphers 🚀
permissions: read-all
on:
  workflow_dispatch:
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "🎉 Step of the job is running on ${{ runner.os }}!"
