name: Lab50 SARIF
run-name: Lab50 - ${{ github.actor }} is creating SARIF reports 🚀
permissions: read-all
on:
  workflow_dispatch:
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "🎉 Step of the job is running on ${{ runner.os }}!"
